// Auto-generated by rotate_guidelines.py
// Source: guidelines.h
// Rotation: -5 degrees around (0, 0), counter-clockwise
//
// Guidelines for TL L44 tileboard DQM plots.
//   hline{i}_x / hline{i}_y : polyline between sub-group i and i+1
//   left_env_* / right_env_*: side envelopes
//   hlines_x[i], hlines_y[i], hlines_n[i]: loop-friendly index arrays.
#pragma once

namespace guidelines_m5deg {

static const double hline0_x[] = {
       0.0000,    2.5807,    5.1602,    7.7371,   10.3104,   12.8789,   15.4411,   17.9960,
      20.5424
};
static const int    n_hline0_x = 9;

static const double hline0_y[] = {
     118.2990,  118.2708,  118.1864,  118.0457,  117.8488,  117.5958,  117.2869,  116.9222,
     116.5017
};
static const int    n_hline0_y = 9;

static const double hline1_x[] = {
      -0.0000,    3.3530,    6.7045,   10.0527,   13.3963,   16.7334,   20.0625,   23.3821,
      26.6906
};
static const int    n_hline1_x = 9;

static const double hline1_y[] = {
     153.7050,  153.6684,  153.5587,  153.3759,  153.1201,  152.7914,  152.3900,  151.9161,
     151.3699
};
static const int    n_hline1_y = 9;

static const double hline2_x[] = {
      -0.0000,    3.9925,    7.9831,   11.9699,   15.9510,   19.9245,   23.8885,   27.8412,
      31.7806
};
static const int    n_hline2_x = 9;

static const double hline2_y[] = {
     183.0170,  182.9734,  182.8428,  182.6251,  182.3206,  181.9292,  181.4513,  180.8869,
     180.2366
};
static const int    n_hline2_y = 9;

static const double hline3_x[] = {
      -0.0000,    4.7539,    9.5056,   14.2526,   18.9930,   23.7243,   28.4442,   33.1507,
      37.8414
};
static const int    n_hline3_x = 9;

static const double hline3_y[] = {
     217.9200,  217.8681,  217.7126,  217.4534,  217.0907,  216.6247,  216.0557,  215.3837,
     214.6093
};
static const int    n_hline3_y = 9;

static const double* hlines_x[] = { hline0_x, hline1_x, hline2_x, hline3_x };
static const double* hlines_y[] = { hline0_y, hline1_y, hline2_y, hline3_y };
static const int     hlines_n[] = { n_hline0_x, n_hline1_x, n_hline2_x, n_hline3_x };
static const int     n_hlines   = 4;

static const double left_env_x[] = {
       0.0001,    0.0000,   -0.0000,    0.0000,   -0.0000,    0.0000,   -0.0000,   -0.0000,
      -0.0000,   -0.0000,   -0.0000,    0.0000,   -0.0000,   -0.0000,    0.0000,   -0.0000,
       0.0000,   -0.0000,    0.0000,    0.0000,    0.0000,    0.0000,   -0.0000,    0.0000,
      -0.0000,   -0.0000,   -0.0001,    0.0000,   -0.0000,    0.0000,    0.0000,   -0.0000,
       0.0000,   -0.0000,   -0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000,
       0.0000,   -0.0000
};
static const int    n_left_env_x = 42;

static const double left_env_y[] = {
     106.0980,  108.4120,  110.8300,  113.2480,  115.7730,  118.2990,  120.9370,  123.5750,
     126.3310,  129.0870,  131.9660,  134.8450,  137.8520,  140.8590,  144.0000,  147.1420,
     150.4230,  153.7050,  157.1330,  160.5600,  164.1410,  167.7220,  171.4620,  175.2030,
     179.1100,  183.0170,  187.0990,  191.1800,  195.4440,  199.7080,  204.1610,  208.6150,
     213.2670,  217.9200,  222.7800,  227.6400,  232.7160,  237.7930,  243.0960,  248.3990,
     253.9390,  259.4790
};
static const int    n_left_env_y = 42;

static const double right_env_x[] = {
      18.4237,   18.8255,   19.2455,   19.6653,   20.1038,   20.5424,   21.0005,   21.4586,
      21.9372,   22.4158,   22.9157,   23.4156,   23.9378,   24.4599,   25.0053,   25.5510,
      26.1207,   26.6906,   27.2858,   27.8809,   28.5028,   29.1246,   29.7741,   30.4236,
      31.1022,   31.7806,   32.4894,   33.1980,   33.9385,   34.6789,   35.4522,   36.2256,
      37.0334,   37.8414,   38.6854,   39.5292,   40.4107,   41.2923,   42.2132,   43.1340,
      44.0960,   45.0581
};
static const int    n_right_env_x = 42;

static const double right_env_y[] = {
     104.4862,  106.7650,  109.1463,  111.5276,  114.0141,  116.5017,  119.0997,  121.6977,
     124.4118,  127.1259,  129.9611,  132.7964,  135.7577,  138.7190,  141.8123,  144.9066,
     148.1377,  151.3699,  154.7458,  158.1207,  161.6473,  165.1740,  168.8571,  172.5413,
     176.3889,  180.2366,  184.2565,  188.2755,  192.4748,  196.6740,  201.0593,  205.4457,
     210.0270,  214.6093,  219.3955,  224.1817,  229.1805,  234.1804,  239.4028,  244.6253,
     250.0811,  255.5369
};
static const int    n_right_env_y = 42;

} // namespace guidelines_m5deg
