// Auto-generated by rotate_guidelines.py
// Source: guidelines.h
// Rotation: -15 degrees around (0, 0), counter-clockwise
//
// Guidelines for TL L44 tileboard DQM plots.
//   hline{i}_x / hline{i}_y : polyline between sub-group i and i+1
//   left_env_* / right_env_*: side envelopes
//   hlines_x[i], hlines_y[i], hlines_n[i]: loop-friendly index arrays.
#pragma once

namespace guidelines_m15deg {

static const double hline0_x[] = {
      20.5424,   23.0790,   25.6046,   28.1180,   30.6180,   33.1035,   35.5732,   38.0259,
      40.4606
};
static const int    n_hline0_x = 9;

static const double hline0_y[] = {
     116.5017,  116.0259,  115.4948,  114.9088,  114.2681,  113.5729,  112.8238,  112.0209,
     111.1647
};
static const int    n_hline0_y = 9;

static const double hline1_x[] = {
      26.6906,   29.9863,   33.2679,   36.5335,   39.7818,   43.0112,   46.2200,   49.4069,
      52.5702
};
static const int    n_hline1_x = 9;

static const double hline1_y[] = {
     151.3699,  150.7516,  150.0616,  149.3001,  148.4676,  147.5644,  146.5911,  145.5479,
     144.4354
};
static const int    n_hline1_y = 9;

static const double hline2_x[] = {
      31.7806,   35.7048,   39.6121,   43.5005,   47.3683,   51.2135,   55.0343,   58.8289,
      62.5955
};
static const int    n_hline2_x = 9;

static const double hline2_y[] = {
     180.2366,  179.5003,  178.6788,  177.7721,  176.7808,  175.7054,  174.5464,  173.3043,
     171.9798
};
static const int    n_hline2_y = 9;

static const double hline3_x[] = {
      37.8414,   42.5141,   47.1666,   51.7965,   56.4018,   60.9803,   65.5298,   70.0480,
      74.5330
};
static const int    n_hline3_x = 9;

static const double hline3_y[] = {
     214.6093,  213.7327,  212.7544,  211.6748,  210.4946,  209.2140,  207.8340,  206.3550,
     204.7778
};
static const int    n_hline3_y = 9;

static const double* hlines_x[] = { hline0_x, hline1_x, hline2_x, hline3_x };
static const double* hlines_y[] = { hline0_y, hline1_y, hline2_y, hline3_y };
static const int     hlines_n[] = { n_hline0_x, n_hline1_x, n_hline2_x, n_hline3_x };
static const int     n_hlines   = 4;

static const double left_env_x[] = {
      18.4238,   18.8256,   19.2454,   19.6653,   20.1037,   20.5424,   21.0004,   21.4586,
      21.9371,   22.4157,   22.9156,   23.4156,   23.9377,   24.4599,   25.0054,   25.5509,
      26.1207,   26.6906,   27.2859,   27.8810,   28.5028,   29.1247,   29.7741,   30.4237,
      31.1021,   31.7806,   32.4893,   33.1981,   33.9385,   34.6789,   35.4522,   36.2256,
      37.0335,   37.8414,   38.6853,   39.5293,   40.4107,   41.2923,   42.2132,   43.1340,
      44.0961,   45.0580
};
static const int    n_left_env_x = 42;

static const double left_env_y[] = {
     104.4862,  106.7650,  109.1463,  111.5275,  114.0141,  116.5017,  119.0997,  121.6977,
     124.4118,  127.1259,  129.9611,  132.7964,  135.7577,  138.7191,  141.8123,  144.9066,
     148.1377,  151.3699,  154.7458,  158.1207,  161.6473,  165.1739,  168.8571,  172.5413,
     176.3889,  180.2366,  184.2565,  188.2755,  192.4748,  196.6740,  201.0593,  205.4457,
     210.0270,  214.6093,  219.3955,  224.1817,  229.1805,  234.1804,  239.4028,  244.6253,
     250.0811,  255.5369
};
static const int    n_left_env_y = 42;

static const double right_env_x[] = {
      36.2876,   37.0791,   37.9061,   38.7331,   39.5967,   40.4606,   41.3629,   42.2652,
      43.2078,   44.1504,   45.1350,   46.1197,   47.1482,   48.1766,   49.2509,   50.3256,
      51.4477,   52.5702,   53.7426,   54.9147,   56.1395,   57.3643,   58.6435,   59.9229,
      61.2593,   62.5955,   63.9917,   65.3874,   66.8458,   68.3042,   69.8272,   71.3505,
      72.9416,   74.5330,   76.1953,   77.8574,   79.5935,   81.3300,   83.1437,   84.9575,
      86.8522,   88.7471
};
static const int    n_right_env_x = 42;

static const double right_env_y[] = {
      99.6996,  101.8740,  104.1462,  106.4184,  108.7910,  111.1647,  113.6436,  116.1225,
     118.7123,  121.3021,  124.0074,  126.7129,  129.5385,  132.3642,  135.3157,  138.2683,
     141.3514,  144.4354,  147.6568,  150.8770,  154.2421,  157.6072,  161.1215,  164.6370,
     168.3083,  171.9798,  175.8155,  179.6504,  183.6573,  187.6642,  191.8486,  196.0340,
     200.4055,  204.7778,  209.3448,  213.9117,  218.6815,  223.4523,  228.4355,  233.4187,
     238.6246,  243.8305
};
static const int    n_right_env_y = 42;

} // namespace guidelines_m15deg
